namespace AMG.Enums.ChatServiceEnums
{
    public enum PhraseSourceEnum
    {
        Base,   // shipped with the mod (DefaultPhraseBank.json)
        Ai,     // generated by the AI, not reviewed yet (AIPhraseBank.json)
        User    // reviewed, or added by the player (VividPhraseBank.json)
    }
}